name: unicodedata2 13.0.0.post2

defaults:
  run:
    shell: bash

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.2

      - name: Fetch source distribution
        run: |
          curl https://files.pythonhosted.org/packages/b8/db/a5d9a7649c2eb2681c30850617b83e1295c3a5bebcdb05908e1da11ed8b7/unicodedata2-13.0.0.post2.tar.gz | tar xvz
          mv unicodedata2-13.0.0.post2/* .

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
          CIBW_BUILD: "cp*"
          CIBW_ARCHS_MACOS: universal2

      - name: Checksum
        uses: Huy-Ngo/gha-sha@v1.1.0
        with:
          glob: 'wheelhouse/*.whl'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'Release: unicodedata2-13.0.0.post2'
          files: wheelhouse/*.whl
          tag_name: unicodedata2-13.0.0.post2
